/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    InfoPanel: typeof import('./components/InfoPanel.vue')['default']
    LegendDec: typeof import('./components/LegendDec.vue')['default']
    LegendPct: typeof import('./components/LegendPct.vue')['default']
    LegendRank: typeof import('./components/LegendRank.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
